### ISSUE TITLE
[MimeKit.MimeMessage]::new() throws an error when using standard library in Net Framework 4.8 #683

### ISSUE THREAD

**Issue by msignori1** [jstedfast/MimeKit#751]
I'm sorry but i'm afraid that Mimekit 3.1.0 has the same error that seems resolved in June '21 and closed

In my local webserver (Framework 4.0.30319) when execute
myM = New MimeKit.MimeMessage
it's OK
but in my provider server (same framework but ASP.NET Version:4.8.4465.0)
returns
"The type initializer for 'MimeKit.ParserOptions' threw an exception"

There's some code that i can write for forcing to use MimeKit with a previous version of ASP.NET ? Or can you take a look if older bug is really closed with Mimekit 3.1.0 ?
Thanks
Massimo Signori

**Comment by jstedfast** [comment]
How handy are you with a debugger?

If you are hitting this, the most likely cause is the loading of character encodings in the [CharsetUtils](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Utils/CharsetUtils.cs#L40) static .ctor.

I don't seem to have any luck reproducing this issue so I don't know what is causing the issue.

The issue that you are referring to from July was about calling `System.Text.Encoding.RegisterProvider (System.Text.CodePagesEncodingProvider.Instance);` in .NET 5.0 (and .NETStandard) because projects may or may not have included the [System.Text.Encoding.CodePages](https://www.nuget.org/packages/System.Text.Encoding.CodePages/) nuget package, so it would throw an exception. The fix I implemented to resolve that issue was to use System.Reflection.

... but that logic is only used for .NET >= 5.0 and .NETStandard, not .NET Framework (including v4.8). You can see that with the `#if NETSTANDARD || NET5_0_OR_GREATER` code block.

.NET Framework already has the various character encodings built in (unlike .NET 5.0 and .NETStandard).

**Comment by jstedfast** [comment]
Maybe the problem is that you are running it on .NET Framework v4.8 but referencing a .NETStandard 2.x assembly?

Try the next build from the [MyGet](https://www.myget.org/feed/mimekit/package/nuget/MimeKit) feed. It should be v3.1.0.309.

**Comment by msignori1** [comment]
Nothing, the next build doesn't resolve the problem.
I do all i can do but unsuccessful.
The funny thing is that in my local server everything works perfectly (also with stable 3.1.0, 3.0.0 etc... version) and i'm not surprise because you say me that older bug reference with NET >=5.0.
Other details i can give to you are:
my pc, visual studio and local server are in ITALIAN LANGUAGE
my code is compiled for Framework 4.6.1 (but i try it also with 4.8)
my local server running on .NET Framework:4.0.30319 and ASP.NET:4.7.3770.0
my provider server running on .NET Framework Version:4.0.30319 and ASP.NET Version:4.8.4465.0 BUT IN ENGLISH LANGUAGE
It'all OK in all servers (also in my provider's server) when create SMTPClient object (New MailKit.Net.Smtp.SmtpClient)
The error "The type initializer for 'MimeKit.ParserOptions' threw an exception" give to me at creation MimeMessage object (New MimeKit.MimeMessage) only in my provider's server
---
At the moment i develop a workaround for my app using NetMail (it's awful) but i hope to help you for understand why it happens and i hope that you found a solution.
Thanks in advance

**Comment by jstedfast** [comment]
In your program, before making any calls to MimeKit, try adding this line:

```csharp
System.Text.Encoding.RegisterProvider (System.Text.CodePagesEncodingProvider.Instance);
```

And make sure that you add the [System.Text.Encoding.CodePages](https://www.nuget.org/packages/System.Text.Encoding.CodePages/6.0.0) nuget.

**Comment by msignori1** [comment]
I dont' catch error intentionally and i have Server Error:

Exception Details: System.MethodAccessException: Attempt by security transparent method '...SMTPClient..ctor()' to access security critical method 'System.Text.Encoding.RegisterProvider(System.Text.EncodingProvider)' failed.

Assembly Version=1.4.8.0, Culture=neutral, PublicKeyToken=null' is partially trusted, which causes the CLR to make it entirely security transparent regardless of any transparency annotations in the assembly itself.  In order to access security critical code, this assembly must be fully trusted.

It's maybe the right way for goal ?

**Comment by jstedfast** [comment]
Is SMTPClient your wrapper?

MimeKit/MailKit need access to the entire spectrum of character encodings and it appears that your ASP.NET environment does not provide them by default (hence the exceptions you've been getting in MimeKit's CharsetUtils).

Starting with .NET Framework v4.6.1, the only character encodings that are guaranteed to be included for ASP.NET are Unicode and ASCII encodings, but mail uses a whole lot more than that.

To facilitate access to a larger variety of character encodings (such as iso-8859-1, etc), a System.Text.Encoding.RegisterProvider() method was introduced to make character encoding support become modular.

**Comment by msignori1** [comment]
No, i compiled a class for testing, but for more details now i write code in web pages
I attach errors result with or without  System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance) before all lines code
I suppose there are restrictions in my server's provider that i haven't in my local server. But i hope that this errors help you to understand why higher permission's are necessary or are required
![Error1](https://user-images.githubusercontent.com/98576345/151909880-d9fb5815-09ab-4332-8be4-74652cf4ff62.PNG)
![Error2](https://user-images.githubusercontent.com/98576345/151909892-7f3b692c-0d9a-428e-b078-8e5066074f2e.PNG)

**Comment by jstedfast** [comment]
AH, you aren't going to be able to use MimeKit unless you can allow unsafe code to run.

**Comment by msignori1** [comment]
Ok but as you will have understood i'm a beginner...
can i ask to my provider to allow it? Or i can insert some directive in web.config ?
I doomed forever to use NET.Mail component in that server ?

**Comment by jstedfast** [comment]
I actually don't know how to do it. I've never gotten familiar with ASP.NET development. I only focus on backend development.

I think it's a registry key that needs to be set/changed, but I'm not sure and whether or not your hosting service will allow that change is something that probably depends on the service.

**Comment by msignori1** [comment]
OK, thanks for your time spent for me. I'll update you if I find a way to run MimeKit also in my provider's server.

**Comment by jstedfast** [comment]
Cool and good luck. It may be worth asking on StackOverflow.com what needs to be done to allow unsafe code to run.
